### ISSUE TITLE
Add function removeEventListener

### ISSUE THREAD

**Issue by Flet** [shama/base-element#12]
Does it make sense to add a [removeEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener) function as well for symmetry?

This should also make it possible to do more sugary things like `.once()`

**Comment by shama** [comment]
It probably does. :)

I've been waiting until I needed it or someone else needed before adding though. If we do add, I think we should look for an existing event library that does this well (or just use `require('events').EventEmitter`).

**Comment by bendrucker** [comment]
Just did some looking and didn't find anything. Bunch of crap hogging all the good names too ;)

I'll go write this once I figure out what to call it
