### ISSUE TITLE
Document setTimeout delay rationale

### ISSUE THREAD

**Issue by bendrucker** [shama/base-element#21]
virtual-dom definitely requires you to wait until the next tick in hooks to be sure that DOM element has actually been inserted. base-element uses a timeout of 10 for load/unload events: https://github.com/shama/base-element/blob/95f5ec27eb49bf3aa118e1c003f31718fe9d927b/index.js#L72-L74

Why 10ms via `setTimeout` instead of just `nextTick`?

**Comment by shama** [comment]
Hmm good call. `nextTick` would probably be better or even [nextback](https://github.com/wearefractal/nextback) which will try `process.setImmediate` first and then `process.nextTick` (assuming those work). Or maybe another lib that does it well?

It's too bad the hooks still require this.

**Comment by bendrucker** [comment]
[next-tick](https://www.npmjs.com/package/next-tick) is more popular and more robust. Wish I could manage to dig up the link, but Raynos has mentioned that the need to defer to ensure the element is in the DOM is considered a feature. The alternative would be to offer explicit APIs around element creation vs insertion.

**Comment by shama** [comment]
:+1:
