### ISSUE TITLE
replaceChild vs appendChild

### ISSUE THREAD

**Issue by shama** [shama/base-element#23]
I'm working on better mounting elements that were initially server rendered and looking for feedback 

/cc @yoshuawuyts @bendrucker @chinedufn @sethvincent

Currently if a server renders `<div class="app">Loading</div>` and an element is loaded with `createElement(document.querySelector('.app'))` the resulting HTML is:

`<div class="app">Loading<div class="app">Client Side Loaded</div></div>` because the attach point always appends. We want to `replaceChild` instead to get the following HTML:

`<div class="app">Client Side Loaded</div>`

Which solution is preferred?

A) **Leave attaching up to the user**
_This is what I currently do but it's a bit verbose_ 

``` js
var el = createElement()
document.querySelector('.app').appendChild(el.element)
// or to mount
document.body.replaceChild(el.element, document.querySelector('.app'))
```

B) **Detect if the attaching node is the same as rendered**
_The most simplest for the end user but a bit magical_
We could check if the node has the same id or class and assume the user wants to replaceChild instead of appendChild:

``` html
<div class="app loading">Loading</div>
```

``` js
var el = createElement(document.querySelector('.app'))
// "el" is a div with the class "app" so we replace instead of append
```

C) **Add methods to explicitly call**
_Adds more APIs to all elements which isn't desired_

``` js
var el = createElement()
el.appendTo(document.body)
// or to mount
el.mountTo(document.querySelector('.app'))
```

Thanks!

**Comment by yoshuawuyts** [comment]
I vote for option A: browser methods are standardized, transparent and keep the module scope more focused (e.g. only concerned about creating elements, not attaching).

**Comment by bendrucker** [comment]
A for me as well

**Comment by chinedufn** [comment]
I think it's worth keeping in mind that `base-element` [already concerns itself with attaching](https://github.com/shama/base-element/blob/master/index.js#L46-L48)

Given this I can see an argument being made for C.

---

I think that the user should be 100% responsible for attaching, but I can also see how having `base-element` handle attaching [might be very handy/natural when working with for some of the popular js frameworks](https://github.com/shama/base-element/blob/master/examples/angular.js#L16-L19) out there. I don't use any so I won't comment further here.

---

Option A for me

**Comment by sethvincent** [comment]
Option A seems like the right thing to do.

What if there were generic helper modules for `mountTo()`, `appendTo()` or even `prependTo()`? 

Maybe unnecessary, but could be useful.

Usage might look something like:

``` js
var mountTo = require('mount-to')
var el = createElement()

mountTo(document.querySelector('.app'), el)
```

**Comment by shama** [comment]
:+1: Option A it is! Thanks all! Very much appreciated!

@sethvincent The separate module is a great idea to reduce the verbosity too, thanks!
