### ISSUE TITLE
.toString()?

### ISSUE THREAD

**Issue by yoshuawuyts** [shama/base-element#5]
When rendering on the server it can be neat to implement a `.toString()` function (or equivalent) to render components to `html`. I'm not sure what the tradeoffs are; but I think it's feasible to implement for every component. Thanks!
### See Also
- [vdom-to-html](https://github.com/nthtran/vdom-to-html)

**Comment by yoshuawuyts** [comment]
Guess this would be shorthand for https://github.com/shama/base-element/blob/master/examples/server-side.js#L24-L31. Thinking the interface would look something like:

``` js
const str = el.toString(['This is', 'the initial', 'content'])
```

**Comment by shama** [comment]
+1 That's a good idea. Because then we could perform a render first too in case `element` hasn't been created.
