### ISSUE TITLE
Rename `.on()`?

### ISSUE THREAD

**Issue by shama** [shama/base-element#7]
Originally I named it `.on()` for readability, such as `el.on('click')` or `el.on('selected')`. But I understand that is a commonly used name so maybe another would be better suited. Initiated by this: https://twitter.com/yoshuawuyts/status/597563041119608832

@yoshuawuyts Could you elaborate more on why `.attachListener()` would be a better name? Thanks!

**Comment by shama** [comment]
Pinging @yoshuawuyts @bendrucker @sethvincent for an opinion on whether or not `.on()` should be renamed. I am indifferent. Thanks for the input!

**Comment by shama** [comment]
Also @Flet, thanks!

**Comment by yoshuawuyts** [comment]
Oh shoot, forgot to come back on this.

I really like the `.on()` name to interact with, but as was pointed out to me by other developers it isn't compatible with how other elements in the browser work. Instead we might want to consider [`EventTarget.addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener). This way elements created with `base-element` can be used with _any_ library that knows how to deal with regular DOM listeners. 

There's a (broken) example of how this could be done [here](https://github.com/yoshuawuyts/xhr-form/blob/master/index.js) using [synthetic-dom-events](https://www.npmjs.com/package/synthetic-dom-events).

I think that would make a reasonable base, at a higher level `.on()` could be implemented by a system similar to [`dom-wrap`](https://github.com/juliangruber/dom-wrap) or [`dom-on`](https://www.npmjs.com/package/dom-on).

Does this make sense?

**Comment by bendrucker** [comment]
+1 to `addEventListener`. I think this could be like standard in that teams could publish `${name}-standard` or a scoped npm package with the sugar methods they want.

**Comment by shama** [comment]
Ah interesting, that makes sense. I am also now +1 to `addEventListener`. Thanks!

**Comment by Flet** [comment]
This is sensible!

**Comment by yoshuawuyts** [comment]
wooh! :tada:
