### ISSUE TITLE
Default __appendTo__ to false instead of document.body

### ISSUE THREAD

**Issue by bendrucker** [shama/base-element#9]
Wanted to propose this for a future breaking version. I'm finding myself wanting to output a vtree from `render` without any DOM side effects far more often than I'm attaching components to the body. Super trivial to change the default in userland in the mean time.

**Comment by shama** [comment]
:+1: Sounds like a better default.

**Comment by bendrucker** [comment]
Any other breaking changes to consider (#7)? Maybe not worth a breaking change when users can do it for now:

``` js
function MyBase (element) {
  BaseElement.call(this, element || false)
}
```
